### ISSUE TITLE
Add to PostHTML organization 

### ISSUE THREAD

**Issue by cossssmin** [ahmed3hamdan/posthtml-rtl#1]
Hi there, just discovered your plugin. Would you be willing to move it to the PostHTML org, so it can be more visible and also get help from the core team?

You’d retain full ownership of course, it would just live under `posthtml/posthtml-rtl`.

Thanks! 😊

**Comment by ahmed3hamdan** [comment]
Hi @cossssmin,

Good idea. Let's move the repository to `posthtml/posthtml-rtl`.

Regards,

**Comment by cossssmin** [comment]
Cool, you'll need to start the transfer in the repo's Settings and we'll assist setting it up in the org 👍

**Comment by ahmed3hamdan** [comment]
I was not able to send transfer request to `posthtml` organization. So, I sent transfer request to you

**Comment by cossssmin** [comment]
Done, thank you. Please check your admin rights for it, everything should be the same 👍

**Comment by cossssmin** [comment]
@ahmed3hamdan I'd like to work on updating this plugin, including adding support for both ESM/CJS. 

Can you please add me to the NPM collaborators so I can publish a new release once done? Thanks!

**Comment by ahmed3hamdan** [comment]
@cossssmin I've invited you.

**Comment by cossssmin** [comment]
Got it, thanks!
